.TH MESSAGE_LOGGER 1
.SH NAME
message_logger - BigWorld cluster logging daemon

.SH SYNOPSIS
.B message_logger
[ \fB--daemon\fR ]
[ \fB-u\fR \fIuid\fR ]
[ \fB-p\fR \fIprocess_type\fR ]
[ \fB-d\fR \fIprocess_type\fR ]
[ \fB-l\fR \fIlogger_id\fR ]
[ \fB-v\fR ]
[ \fB--version\fR ]
[ \fB-c|--config\fR \fIfile\fR ]
[ \fB-h|--help\fR ]
[ \fB-t|--text\fR ]
[ \fB-q|--quiet\fR ]
[ \fB-o\fR \fIfile\fR ]
[ \fB-e\fR \fIfile\fR ]
[ \fB+{log level}\fR ]
[ \fB-{log level}\fR ]
[ \fIlog_directory\fR ]

.SH SUMMARY
.B MessageLogger
is a process used for logging output from BigWorld processes
within a cluster. It is a standalone Linux process that can be run on
any machine in a BigWorld cluster that is running BWMachined.

.SH OPTIONS
.SS "Generic Program Options"
.TP
.BI \-c " config"
Specify a config file to use.

If a configuration file is not specified, MessageLogger will attempt to
locate the tools directory in \fI/etc/bigworld.conf\fR under which it will look
for \fImessagelogger/messagelogger.conf\fR.

If \fI/etc/bigworld.conf\fR does not exist, the default is
\fImessage_logger.conf\fR in the current directory.
.TP
.B \-\^\-daemon
Run the MessageLogger process as a daemon.
.TP
.BI \-e " file"
Redirect standard error to \fIfile\fR. This option is useful when
running MessageLogger as a daemon.
.TP
.B \-\^\-help
Print a usage message briefly summarizing these command-line options,
then exit.
.TP
.BI \-o " file"
Redirect standard output to \fIfile\fR. This option is useful when
running MessageLogger as a daemon.
.TP
.BR \-q ", " \-\^\-quiet
Quiet mode. Do not display messages generated by this process. By default these
are output to standard error.
.TP
.BR \-t ", " \-\^\-text
Generate text logs as well as binary logs.
.TP
.B \-v
Enable verbose debugging output.
.TP
.B \-\^\-version
Print the version of message_logger binary, then exit.
.TP
.B log_directory
Output will be stored in this directory. If not specified, this will be read
from the config file \fBlogdir\fR option.
.SS "General Log Filters"
.TP
.BI \-l " logger_id"
Only log messages destined for \fIlogger_id\fR.

Logs for the Tools process type do not have a logger ID associated with them
and will not be filtered out (this allows server start messages to be recorded
and enables log-viewing functionality from the last server start time).
.TP
.BI \-u " uid"
Log only messages from processes run by the user with the specified uid. If
\fIuid\fR is '\fIall\fR' or not specified, messages from all users will be
logged.
.SS "Process Type Log Filter"
.TP
.BI \-d " process_type"
Disable logging of messages from processes with process type name
\fIprocess_type\fR. Multiple names may be specified using multiple \fB\-d\fR
options. Process type inclusion (\fB\-p\fR) and exclusion (\fB\-d\fR) options
should not be used together. By default messages from processes of any name are
logged.
.TP
.BI \-p " process_type"
Enable logging of messages from processes with process type name
\fIprocess_type\fR. Specifying this option disables logging of other process
types, however multiple names may be specified using multiple \fB\-p\fR options.
Process type inclusion (\fB\-p\fR) and exclusion (\fB\-d\fR) options should not
be used together. By default messages from processes of any name are logged.
.TP
Appropriate \fIprocess_type\fR names include:
\fBCellAppMgr\fR,
\fBCellApp\fR,
\fBBaseApp\fR,
\fBBaseAppMgr\fR,
\fBDBMgr\fR,
\fBDBApp\fR,
\fBDBAppMgr\fR,
\fBLoginApp\fR,
\fBServiceApp\fR,
\fBTools\fR.
.SS "Log Level Filter"
.TP
.BI -[TRACE|DEBUG|INFO|NOTICE|WARNING|ERROR|CRITICAL|HACK|ASSET]
Disable logging of a specific log level. Multiple log levels may be excluded by
using multiple instances of this option. Log level exclusion and inclusion
options should not be used together. By default all log levels are logged.
.TP
.BI +[TRACE|DEBUG|INFO|NOTICE|WARNING|ERROR|CRITICAL|HACK|ASSET]
Enable logging of a specific log level. Specifying this option disables logging
of other log levels, however multiple log levels may be included by using
multiple instances of this option. Log level exclusion and inclusion options
should not be used together. By default all log levels are logged.
.SH SIGNALS
.SS SIGHUP
Begin rolling logs. This process may cause the server to slow down. As this is
only part of the rolling and archiving process, it is instead recommended to
use the log rotation functionality of the MessageLogger init.d script:
.IP
\fB/etc/init.d/bw_message_logger logrotate\fR
.SS SIGUSR1
Validate and update the hostnames cache, both on file and on disk. Once the
hostnames cache has been updated it will no longer be possible to search the
logs for outdated hostnames. Activating the hostnames cache validation process
on a very large cluster of machines during a heavy load may impact the
performance of MessageLogger.
.\" .SH FILES
.SH EXAMPLES
.P
Run MessageLogger for all users using a specific config file
\fI/etc/bigworld/message_logger.conf\fR, excluding trace and debug log levels and
logging to \fI/var/log/bigworld/message_logger\fR.
.IP
\fBmessage_logger -u all -c /etc/bigworld/message_logger.conf -TRACE -DEBUG
/var/log/bigworld/message_logger\fR
.P
Run MessageLogger for uid 1234, using a config file in the current
directory and recording only error and critical log levels. The log output
directory will be read from the config file \fBlogdir\fR option.
.IP
\fBmessage_logger -u 1234 -c ./message_logger.conf +ERROR +CRITICAL\fR
.SH "EXIT STATUS"
.B MessageLogger
will exit with a return status of 0 on graceful shutdown or a value of 1 if a fatal
error was encountered during operations.
.SH "SEE ALSO"
.SS "BigWorld Tools"
mltar(1)
.br
